<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KIS4N2E" failures="2" tests="3" name="Test" time="44.161" errors="0" timestamp="2024-01-10T13:44:19 IST">
  <testcase classname="coverFoxTest.CF_TC556_Validate_pinCode_ErrorMsg" name="validate_pinCode_ErrorMsg" time="0.094"/>
  <testcase classname="coverFoxTest.CF_TC555_Validate_search_results_for_healthcare_policies" name="validateTestPlansFromTextAndBanners" time="13.125">
    <failure type="java.lang.AssertionError" message="Text results are matching with Banner results, TC is failed expected [49] but found [10]">
      <![CDATA[java.lang.AssertionError: Text results are matching with Banner results, TC is failed expected [49] but found [10]
at coverFoxTest.CF_TC555_Validate_search_results_for_healthcare_policies.validateTestPlansFromTextAndBanners(CF_TC555_Validate_search_results_for_healthcare_policies.java:86)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validateTestPlansFromTextAndBanners -->
  <testcase classname="coverFoxTest.CF_TC555_Validate_search_results_for_healthcare_policies" name="validateTestPlansFromTextAndBanners" time="18.673">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)&amp;quot; because the return value of &amp;quot;java.lang.ThreadLocal.get()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.fail(java.lang.Throwable)" because the return value of "java.lang.ThreadLocal.get()" is null
at listeners.ListenerCoverFox.onTestFailure(ListenerCoverFox.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateTestPlansFromTextAndBanners -->
</testsuite> <!-- Test -->
